name: Deploy to Surge

on:
  push:
    branches:
      - master  # Cambia "master" si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge.sh
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
